version: '3.8'

services:
  langgraph-server:
    image: langchain/langgraph-server:latest
    ports:
      - "8000:8000"
    networks:
      - langgraph-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    networks:
      - langgraph-network
    environment:
      - LANGGRAPH_SERVER_URL=http://langgraph-server:8000
    depends_on:
      langgraph-server:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/.venv
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  langgraph-network:
    driver: bridge
