name: Backend CI

on:
  push:
    branches: [ "main", "master" ] # Adjust if your main branch has a different name
    paths:
      - 'apps/backend/**'
      - 'packages/common/**' # If common package changes, backend might be affected
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'apps/backend/**'
      - 'packages/common/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/backend # Set working directory for all run steps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # As per original prompt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest tests
        run: pytest
