name: Docker Build and Push Backend

on:
  push:
    branches: [ "main", "master" ] # Adjust if your main branch has a different name
    paths:
      - 'apps/backend/**'
      - 'packages/common/**'
      - '.github/workflows/docker-publish.yml'

env:
  # ghcr.io/github_username/repository_name/image_name:tag
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}/backend

jobs:
  build-and-push-docker-image:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the monorepo root
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
